# Generated by Django 3.2.7 on 2022-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220206_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mawe',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='request',
            field=models.ManyToManyField(related_name='bar_sell', to='myapp.Sell'),
        ),
    ]
