# Generated by Django 3.2.7 on 2022-09-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220708_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mawe',
        ),
    ]
