# Generated by Django 3.2.7 on 2022-09-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_mawe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='regions',
        ),
    ]
